/**
 * server/fileOps.js
 * ------------------------------------------------------------------
 * All filesystem work for the "wiki" page-creation workflow lives
 * here, kept separate from server/index.js (which only wires up HTTP
 * routes). Two responsibilities:
 *
 *  1. DRAFTS (the "temp folder"): each draft is one JSON file under
 *     server/drafts/<id>.json. Saving a draft never touches your real
 *     source code - it's just a scratch space so a half-finished page
 *     isn't lost if you close the tab.
 *
 *  2. PUBLISHING: turns a draft into the real thing - either appends
 *     a topic object into an existing src/data/topics/<key>.js file,
 *     or creates a brand-new category file and registers it in
 *     src/data/topics/index.js. This reuses the EXACT same code
 *     generation logic as the "Generate code" button in the UI
 *     (src/utils/topicCodegen.js) - one function decides what the
 *     code should look like, whether a human pastes it or the server
 *     writes it.
 *
 * NOTE: this file manipulates your real source files with targeted
 * string insertion (find `];` right before `export default`, insert
 * before it) rather than a full JS parser. That's safe here because
 * WE control the exact format of every file it touches (they were
 * all generated by this same codebase) - it is not a general-purpose
 * JS code editor.
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  buildTopicObjectCode,
  buildNewCategoryFileCode,
  slugify,
} from '../src/utils/topicCodegen.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DRAFTS_DIR = path.join(__dirname, 'drafts');
const TOPICS_DIR = path.join(__dirname, '..', 'src', 'data', 'topics');
const INDEX_FILE = path.join(TOPICS_DIR, 'index.js');

// ---------------------------------------------------------------
// Drafts (temp folder)
// ---------------------------------------------------------------

export function listDrafts() {
  const files = fs.readdirSync(DRAFTS_DIR).filter((f) => f.endsWith('.json'));
  return files.map((file) => {
    const raw = fs.readFileSync(path.join(DRAFTS_DIR, file), 'utf-8');
    return JSON.parse(raw);
  });
}

export function saveDraft(draftData) {
  const id = `draft-${Date.now()}`;
  const draft = { id, createdAt: new Date().toISOString(), ...draftData };
  fs.writeFileSync(path.join(DRAFTS_DIR, `${id}.json`), JSON.stringify(draft, null, 2));
  return draft;
}

export function getDraft(id) {
  const filePath = path.join(DRAFTS_DIR, `${id}.json`);
  if (!fs.existsSync(filePath)) return null;
  return JSON.parse(fs.readFileSync(filePath, 'utf-8'));
}

export function deleteDraft(id) {
  const filePath = path.join(DRAFTS_DIR, `${id}.json`);
  if (fs.existsSync(filePath)) fs.unlinkSync(filePath);
}

// ---------------------------------------------------------------
// Publishing (temp folder -> real src/data/topics files)
// ---------------------------------------------------------------

function categoryFilePath(categoryKey) {
  return path.join(TOPICS_DIR, `${categoryKey}.js`);
}

function toCamel(categoryKey) {
  return `${categoryKey.replace(/-([a-z])/g, (_, c) => c.toUpperCase())}Topics`;
}

/** Appends one topic object into an EXISTING category file's array. */
function appendTopicToExistingCategory(categoryKey, topicObjectCode) {
  const filePath = categoryFilePath(categoryKey);
  if (!fs.existsSync(filePath)) {
    throw new Error(`Category file not found: ${categoryKey}.js`);
  }
  const content = fs.readFileSync(filePath, 'utf-8');
  const closingIndex = content.lastIndexOf('];');
  if (closingIndex === -1) {
    throw new Error(`Could not find the array's closing "];" in ${categoryKey}.js`);
  }
  const updated = `${content.slice(0, closingIndex)}${topicObjectCode}\n${content.slice(closingIndex)}`;
  fs.writeFileSync(filePath, updated);
}

/** Creates a brand-new category data file. */
function createCategoryFile(categoryKey, topicObjectCode) {
  const filePath = categoryFilePath(categoryKey);
  if (fs.existsSync(filePath)) {
    throw new Error(`Category file already exists: ${categoryKey}.js`);
  }
  fs.writeFileSync(filePath, buildNewCategoryFileCode(categoryKey, topicObjectCode));
}

/** Registers a new category in src/data/topics/index.js (import + CATEGORIES entry). */
function registerCategoryInIndex(categoryKey, categoryLabel, color, codeLang) {
  const content = fs.readFileSync(INDEX_FILE, 'utf-8');
  const varName = toCamel(categoryKey);

  // 1) insert the import line after the last existing import statement
  const importLineRegex = /^import .+;$/gm;
  let lastImportEnd = -1;
  let match;
  while ((match = importLineRegex.exec(content)) !== null) {
    lastImportEnd = match.index + match[0].length;
  }
  if (lastImportEnd === -1) throw new Error('Could not find any import statements in index.js');

  const importLine = `\nimport ${varName} from './${categoryKey}.js';`;
  let updated = content.slice(0, lastImportEnd) + importLine + content.slice(lastImportEnd);

  // 2) insert a CATEGORIES entry just before the array's closing "];"
  const categoriesStart = updated.indexOf('export const CATEGORIES = [');
  if (categoriesStart === -1) throw new Error('Could not find "export const CATEGORIES = [" in index.js');
  const closingIndex = updated.indexOf('];', categoriesStart);
  if (closingIndex === -1) throw new Error('Could not find the CATEGORIES array\'s closing "];" in index.js');

  const entry = `  {\n    key: ${JSON.stringify(categoryKey)},\n    label: ${JSON.stringify(categoryLabel)},\n    color: ${JSON.stringify(color || '#888888')},\n    codeLang: ${JSON.stringify(codeLang || 'text')},\n    topics: ${varName},\n    tools: [],\n  },\n`;
  updated = updated.slice(0, closingIndex) + entry + updated.slice(closingIndex);

  fs.writeFileSync(INDEX_FILE, updated);
}

/**
 * publishDraft(draft) - the main entry point called by the /publish
 * route. Returns { filesChanged: string[] } on success, throws on
 * any problem (caller is responsible for turning that into an HTTP
 * error response).
 */
export function publishDraft(draft) {
  const topicObjectCode = buildTopicObjectCode({
    slug: draft.slug,
    title: draft.title,
    summary: draft.summary,
    tags: draft.tags,
    gifUrl: draft.gifUrl,
    relatedTool: draft.relatedTool,
    body: draft.body,
  });

  const filesChanged = [];

  if (draft.isNewCategory) {
    const key = slugify(draft.newCategoryKey);
    createCategoryFile(key, topicObjectCode);
    filesChanged.push(`src/data/topics/${key}.js (new)`);

    registerCategoryInIndex(key, draft.newCategoryLabel, draft.newCategoryColor, draft.newCategoryCodeLang);
    filesChanged.push('src/data/topics/index.js (updated)');
  } else {
    appendTopicToExistingCategory(draft.categoryKey, topicObjectCode);
    filesChanged.push(`src/data/topics/${draft.categoryKey}.js (updated)`);
  }

  deleteDraft(draft.id);
  return { filesChanged };
}
