/**
 * src/utils/topicCodegen.js
 * ------------------------------------------------------------------
 * Pure helper functions - no React here. They take plain form values
 * (strings) and return STRINGS of valid JavaScript source code, ready
 * to paste into src/data/topics/*.js.
 *
 * WHY GENERATE TEXT INSTEAD OF WRITING FILES DIRECTLY:
 * A page running in the browser cannot edit files on your hard disk
 * (that's a browser security boundary, not a limitation we chose).
 * So the New Page form's job is to produce the exact code you'd have
 * typed by hand, correctly formatted and safely escaped, and let you
 * paste/download it. Once the Node BFF from the architecture doc
 * exists, this same generated object could instead be POSTed to an
 * endpoint that commits it to GitHub directly - the codegen logic
 * here wouldn't need to change, only what happens with its output.
 *
 * We use JSON.stringify() to turn strings into JS string literals.
 * This is a small trick worth knowing: JSON.stringify('He said "hi"')
 * produces a string that is ALSO valid JavaScript source for that
 * string, with quotes/backslashes/newlines already escaped correctly.
 * That's safer than trying to hand-build template literals, which
 * would break if the user's text happened to contain a backtick.
 */

/** Turn "My Cool Topic!" into "my-cool-topic" - used to suggest a slug
 * from the title while the user types, though they can still edit it. */
export function slugify(text) {
  return text
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

/**
 * buildTopicObjectCode(topic)
 * topic = { slug, title, summary, tags, gifUrl, relatedTool, body }
 * (tags is a comma-separated string as typed in the form, e.g. "java, streams")
 *
 * Returns a formatted object-literal string matching the style used
 * in java.js / json.js / etc., e.g.:
 *   {
 *     slug: "my-topic",
 *     title: "My Topic",
 *     ...
 *   },
 */
export function buildTopicObjectCode(topic) {
  const tagsArray = topic.tags
    .split(',')
    .map((t) => t.trim())
    .filter(Boolean);

  const lines = [
    '  {',
    `    slug: ${JSON.stringify(topic.slug)},`,
    `    title: ${JSON.stringify(topic.title)},`,
    `    summary: ${JSON.stringify(topic.summary)},`,
    `    tags: ${JSON.stringify(tagsArray)},`,
    `    gifUrl: ${topic.gifUrl ? JSON.stringify(topic.gifUrl) : 'null'},`,
    `    relatedTool: ${topic.relatedTool ? JSON.stringify(topic.relatedTool) : 'null'},`,
    `    body: ${JSON.stringify(topic.body)},`,
    '  },',
  ];

  return lines.join('\n');
}

/**
 * buildNewCategoryFileCode(categoryKey, topicObjectCode)
 * Full contents of a brand-new src/data/topics/<categoryKey>.js file,
 * matching the pattern of the existing category files (an array with
 * one topic in it, ready to add more later).
 */
export function buildNewCategoryFileCode(categoryKey, topicObjectCode) {
  const varName = `${categoryKey.replace(/-([a-z])/g, (_, c) => c.toUpperCase())}Topics`;

  return `/**
 * src/data/topics/${categoryKey}.js
 * Generated by the "New Page" form. Same shape as the other files in
 * this folder - see src/data/topics/java.js for the full field guide.
 */

const ${varName} = [
${topicObjectCode}
];

export default ${varName};
`;
}

/**
 * buildIndexRegistrationSnippet(categoryKey, categoryLabel, color, codeLang)
 * The lines you add to src/data/topics/index.js to wire a NEW
 * category file into the app (existing categories don't need this -
 * only creating a category for the first time does).
 */
export function buildIndexRegistrationSnippet(categoryKey, categoryLabel, color = '#888888', codeLang = 'text') {
  const varName = `${categoryKey.replace(/-([a-z])/g, (_, c) => c.toUpperCase())}Topics`;

  return `// 1) Add this import near the top of src/data/topics/index.js:
import ${varName} from './${categoryKey}.js';

// 2) Add this entry to the CATEGORIES array in the same file:
{
  key: ${JSON.stringify(categoryKey)},
  label: ${JSON.stringify(categoryLabel)},
  color: ${JSON.stringify(color)},
  codeLang: ${JSON.stringify(codeLang)},
  topics: ${varName},
  tools: [],
},`;
}

/** Triggers a browser download of `content` as a file named `filename`. */
export function downloadTextFile(filename, content) {
  const blob = new Blob([content], { type: 'text/javascript' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
}
